# Generated by Django 2.1.2 on 2018-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181127_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_lecture',
            field=models.ManyToManyField(blank=True, null=True, to='lectures.Lecture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_product',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('남', '남자'), ('여', '여자')], max_length=1, null=True),
        ),
    ]
