# Generated by Django 2.1.2 on 2018-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181127_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_lecture',
            field=models.ManyToManyField(blank=True, to='lectures.Lecture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
