# Generated by Django 2.1.2 on 2018-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='account_image/account_pic_default.png', upload_to='account_image/'),
        ),
    ]
