# Generated by Django 2.1.2 on 2018-12-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
