# Generated by Django 2.1.2 on 2019-01-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_lecture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_product',
        ),
    ]
