# Generated by Django 2.1.2 on 2019-01-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20190102_0201'),
        ('accounts', '0018_auto_20190101_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='products.Content'),
        ),
    ]
