# Generated by Django 2.1.2 on 2019-02-23 13:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detailAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extraAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='참조주소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='정보제공동의'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='본인소개'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='이메일검증'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('남', '남자'), ('여', '여자')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='account_image/account_pic_default.png', upload_to=accounts.models.user_directory_path, verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='route',
            field=models.CharField(blank=True, choices=[('BLG', '네이버블로그'), ('SRC', '인터넷검색'), ('NWS', '뉴스 및 기사'), ('FBK', '페이스북'), ('ING', '인스타그램'), ('REC', '지인소개'), ('EDU', '강의교육'), ('ETC', '기타')], max_length=5, null=True, verbose_name='가입경로'),
        ),
    ]
