# Generated by Django 2.1.2 on 2018-10-31 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='lecture_image/')),
                ('register_from', models.DateField(blank=True)),
                ('register_to', models.DateField(blank=True)),
                ('period_from', models.DateField(blank=True)),
                ('period_to', models.DateField(blank=True)),
                ('fee', models.IntegerField(blank=True, default=0)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('isDiscount', models.BooleanField(default=False, verbose_name='On Sale')),
                ('sample', models.URLField(blank=True)),
                ('book', models.CharField(blank=True, max_length=200)),
                ('teacher', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('isSale', models.BooleanField(default=False, verbose_name='For Sale')),
                ('isShow', models.BooleanField(default=False, verbose_name='On showing')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('movie', models.URLField(blank=True)),
                ('content', models.TextField(blank=True, max_length=3000)),
                ('file', models.FileField(blank=True, upload_to='data_file/lecture/')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Section'),
        ),
    ]
