# Generated by Django 2.1.2 on 2018-11-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20181101_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='book',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='교재 및 교보재'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lecture_image/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='register_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='register_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data_file/lecture/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.URLField(blank=True, null=True),
        ),
    ]
