# Generated by Django 2.1.2 on 2018-11-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20181106_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='book',
            field=models.CharField(blank=True, max_length=200, verbose_name='교재 및 교보재'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, upload_to='lecture_image/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='data_file/lecture/'),
        ),
    ]
