# Generated by Django 2.1.2 on 2018-11-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20181106_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='image',
            new_name='lecture_image',
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.URLField(blank=True),
        ),
    ]
