# Generated by Django 2.1.2 on 2018-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20181106_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
