# Generated by Django 2.1.2 on 2018-11-11 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_lecture_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
