# Generated by Django 2.1.2 on 2018-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_auto_20181112_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
