# Generated by Django 2.1.2 on 2018-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181112_1523'),
        ('lectures', '0010_lecture_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='material',
        ),
        migrations.AddField(
            model_name='lecture',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
