# Generated by Django 2.1.2 on 2018-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_auto_20181117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='material',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
