# Generated by Django 2.1.2 on 2019-01-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_auto_20181117_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='book',
        ),
    ]
