# Generated by Django 2.1.2 on 2019-01-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0013_remove_lecture_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='teacher',
        ),
    ]
