# Generated by Django 2.1.2 on 2019-01-01 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0014_remove_lecture_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
