# Generated by Django 2.1.2 on 2019-01-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0015_lecture_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='material',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='section',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
