# Generated by Django 2.1.2 on 2019-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='수량'),
        ),
    ]
