# Generated by Django 2.1.2 on 2019-02-24 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190224_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Content'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
