# Generated by Django 2.1.2 on 2018-12-21 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.ForeignKey(on_delete=False, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
