# Generated by Django 2.1.2 on 2018-12-21 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20181221_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
