# Generated by Django 2.1.2 on 2018-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20181221_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
