# Generated by Django 2.1.2 on 2019-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20190107_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_post_to_post',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_to_post_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
