# Generated by Django 2.1.2 on 2019-01-07 09:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20190107_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='게시판 설명'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='게시판'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_post_to_post',
            field=models.BooleanField(blank=True, default=False, verbose_name='대댓글 여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=4000, verbose_name='본문 내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='댓글 순서'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to_post_address',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='대상댓글'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=4000, verbose_name='본문 내용'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
