# Generated by Django 2.1.2 on 2019-01-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20190107_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='순서'),
        ),
    ]
