# Generated by Django 2.1.2 on 2019-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20190107_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(blank=True, verbose_name='업데이트 날짜'),
        ),
    ]
