# Generated by Django 2.1.2 on 2019-02-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20190112_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
    ]
