# Generated by Django 2.1.2 on 2019-06-09 11:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='본문 내용'),
        ),
        migrations.AlterField(
            model_name='serviceusage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='본문 내용'),
        ),
    ]
