# Generated by Django 2.1.2 on 2019-06-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_auto_20190609_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='ServiceUsage',
        ),
    ]
