# Generated by Django 2.1.2 on 2019-02-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0048_auto_20190221_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('address', models.CharField(max_length=250, verbose_name='주소')),
                ('postal_code', models.CharField(max_length=20, verbose_name='우편번호')),
                ('city', models.CharField(max_length=100, verbose_name='시/도')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='주문요청')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='주문수정')),
                ('paid', models.BooleanField(default=False, verbose_name='결제')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='금액')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Content')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
