# Generated by Django 2.1.2 on 2019-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190222_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='infoSave',
            field=models.BooleanField(default=False, verbose_name='반영여부'),
        ),
    ]
