# Generated by Django 2.1.2 on 2019-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address3',
            field=models.CharField(default='', max_length=250, verbose_name='참조주소'),
            preserve_default=False,
        ),
    ]
