# Generated by Django 2.1.2 on 2019-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='금액'),
        ),
    ]
