# Generated by Django 2.1.2 on 2019-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190223_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalCost',
            field=models.PositiveIntegerField(default=0, verbose_name='최종금액'),
        ),
    ]
