# Generated by Django 2.1.2 on 2019-02-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='detailAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address3',
            new_name='extraAddress',
        ),
    ]
