# Generated by Django 2.1.2 on 2019-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190224_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='주문번호'),
        ),
    ]
