# Generated by Django 2.1.2 on 2019-03-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190307_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('001', '상품준비중'), ('002', '배송준비중'), ('003', '배송중'), ('004', '배송완료'), ('005', '기타')], max_length=4, null=True, verbose_name='배송상태'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='orders.Order'),
        ),
    ]
