# Generated by Django 2.1.2 on 2019-03-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190310_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('001', '상품준비중'), ('002', '배송준비중'), ('003', '배송중'), ('004', '배송완료'), ('005', '기타')], default='001', max_length=4, verbose_name='배송상태'),
        ),
    ]
