# Generated by Django 2.1.2 on 2019-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190310_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='배송료'),
        ),
    ]
