# Generated by Django 2.1.2 on 2019-03-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.CharField(choices=[('001', '일반배송'), ('002', '도서산간'), ('003', '착불'), ('004', '직접수령'), ('005', '기타')], default='001', max_length=4, verbose_name='배송료'),
        ),
    ]
