# Generated by Django 2.1.2 on 2019-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190310_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='요청사항'),
        ),
    ]
