# Generated by Django 2.1.2 on 2019-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.CharField(choices=[('001', '미정'), ('002', '확정')], default='001', max_length=4, verbose_name='구매결정'),
        ),
    ]
