# Generated by Django 2.1.2 on 2019-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_imp_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('card', '신용카드'), ('trans', '실시간계좌이체'), ('vbank', '가상계좌'), ('phone', '휴대폰소액결제'), ('samsung', '삼성페이 '), ('kpay', 'KPay'), ('cultureland', '문화상품권 '), ('smartculture', '스마트문상 '), ('happymoney', '해피머니 ')], default='card', max_length=10, verbose_name='결제수단'),
        ),
    ]
