# Generated by Django 2.1.2 on 2019-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20190314_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancel',
            name='order_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='주문번호'),
        ),
    ]
