# Generated by Django 2.1.2 on 2019-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_ordercancel_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tex_free_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='면세금액'),
        ),
    ]
