# Generated by Django 2.1.2 on 2019-03-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_tex_free_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('apply_num', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('bank_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('buyer_addr', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('buyer_email', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('buyer_name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('buyer_postcode', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('buyer_tel', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('cancel_amount', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('cancel_history', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('cancel_reason', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('cancel_receipt_urls', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('cancelled_at', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('card_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('card_name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('card_quota', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('cash_receipt_issued', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('channel', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('currency', models.CharField(blank=True, default='KRW', max_length=500, null=True)),
                ('custom_data', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('escrow', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('fail_reason', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('failed_at', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('imp_uid', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('merchant_uid', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('paid_at', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('pay_method', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('pg_id', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('pg_provider', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('pg_tid', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('receipt_url', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, default='sorry_not_supported_anymore', max_length=500, null=True)),
                ('vbank_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vbank_date', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('vbank_holder', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vbank_issued_at', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('vbank_name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vbank_num', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.CharField(choices=[('001', '일반배송'), ('002', '도서산간'), ('003', '착불'), ('004', '직접수령'), ('005', '기타')], default='001', max_length=4, verbose_name='배송료')),
                ('delivery', models.CharField(choices=[('001', '상품준비중'), ('002', '배송준비중'), ('003', '배송중'), ('004', '배송완료'), ('005', '기타')], default='001', max_length=4, verbose_name='배송상태')),
                ('delivery_agent', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='배송업체')),
                ('delivery_code', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='운송장')),
                ('delivery_note', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='배송사항')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='detailAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='extraAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='imp_uid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderDelivery', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='importinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importInfo', to='orders.Order'),
        ),
    ]
