# Generated by Django 2.1.2 on 2019-03-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20190317_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AlterField(
            model_name='importinfo',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('card', '신용카드'), ('trans', '실시간계좌이체'), ('vbank', '가상계좌'), ('phone', '휴대폰소액결제'), ('samsung', '삼성페이 '), ('kpay', 'KPay'), ('cultureland', '문화상품권 '), ('smartculture', '스마트문상 '), ('happymoney', '해피머니 ')], default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='importinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패')], default=None, max_length=500, null=True),
        ),
    ]
