# Generated by Django 2.1.2 on 2019-03-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20190317_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdelivery',
            old_name='delivery',
            new_name='delivery_status',
        ),
    ]
