# Generated by Django 2.1.2 on 2019-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20190317_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='infoSave',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='detailAddress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='extraAddress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='참조주소'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='우편번호'),
        ),
    ]
