# Generated by Django 2.1.2 on 2019-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20190317_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imp_uid',
            field=models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='아임포트'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='주문번호'),
        ),
    ]
