# Generated by Django 2.1.2 on 2019-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20190317_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercancel',
            old_name='order_no',
            new_name='merchant_uid',
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True, verbose_name='이메일'),
        ),
    ]
