# Generated by Django 2.1.2 on 2019-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20190317_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_agent',
            field=models.CharField(blank=True, choices=[('04', 'CJ대한통운'), ('05', '한진택배'), ('08', '롯데택배'), ('01', '우체국택배'), ('06', '로젠택배'), ('07', 'KG로지스택배'), ('09', 'KG로지스택배(KG옐로우캡)'), ('10', 'KGB택배'), ('11', '일양로지스'), ('12', 'EMS'), ('13', 'DHL'), ('20', '한덱스'), ('21', 'FedEx'), ('14', 'UPS'), ('26', 'USPS'), ('22', '대신택배'), ('23', '경동택배'), ('32', '합동택배'), ('46', 'CU 편의점택배'), ('24', 'CVSnet 편의점택배'), ('25', 'TNT Express'), ('16', '한의사랑택배'), ('15', 'GTX로지스'), ('17', '천일택배'), ('18', '건영택배'), ('28', 'GSMNtoN')], default=None, max_length=3, null=True, verbose_name='배송업체'),
        ),
    ]
