# Generated by Django 2.1.2 on 2019-03-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='result',
            field=models.BooleanField(blank=True, choices=[(True, '구매성공'), (False, '구매실패')], default=False, null=True, verbose_name='구매상태'),
        ),
    ]
