# Generated by Django 2.1.2 on 2018-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(blank=True, upload_to='content_image'),
        ),
    ]
