# Generated by Django 2.1.2 on 2018-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20181025_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='character',
            field=models.ImageField(blank=True, upload_to='character_image'),
        ),
    ]
