# Generated by Django 2.1.2 on 2019-02-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_intro_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intro',
            options={'ordering': ['id']},
        ),
    ]
