# Generated by Django 2.1.2 on 2018-10-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_description', models.TextField(max_length=3000, verbose_name='Content')),
                ('detail_image', models.ImageField(blank=True, upload_to='product_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Title')),
                ('product_cost', models.IntegerField(default=0, verbose_name='Product price')),
                ('product_discount', models.IntegerField(default=0, verbose_name='Discounted price')),
                ('product_isDiscount', models.BooleanField(default=False, verbose_name='For Sale')),
                ('product_description', models.CharField(max_length=300, verbose_name='Description')),
                ('product_file', models.FileField(blank=True, upload_to='data_file/product/')),
                ('product_image', models.ImageField(blank=True, upload_to='product_image/')),
                ('product_moive', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
