# Generated by Django 2.1.2 on 2018-10-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_moive',
            new_name='product_movie',
        ),
    ]
