# Generated by Django 2.1.2 on 2018-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181026_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detail_description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Content'),
        ),
    ]
