# Generated by Django 2.1.2 on 2018-10-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181026_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_isDiscount',
            new_name='product_isSale',
        ),
    ]
