# Generated by Django 2.1.2 on 2018-10-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181026_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_movie',
            field=models.URLField(blank=True),
        ),
    ]
