# Generated by Django 2.1.2 on 2018-10-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_thumbnail',
        ),
    ]
