# Generated by Django 2.1.2 on 2018-11-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181029_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='detail_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='detail_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_isSale',
            new_name='isSale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_movie',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='no title', max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='no title', max_length=200, verbose_name='Title'),
        ),
    ]
