# Generated by Django 2.1.2 on 2018-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181111_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
