# Generated by Django 2.1.2 on 2018-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181112_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='lower_line',
            field=models.BooleanField(default=False, verbose_name='lower line'),
        ),
    ]
