# Generated by Django 2.1.2 on 2018-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_auto_20181117_2206'),
        ('products', '0013_auto_20181112_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_lec',
            field=models.ManyToManyField(to='lectures.Lecture'),
        ),
    ]
