# Generated by Django 2.1.2 on 2018-11-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_related_lec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_lec',
        ),
    ]
