# Generated by Django 2.1.2 on 2018-12-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_related_lec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Link URL'),
        ),
    ]
