# Generated by Django 2.1.2 on 2019-01-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_pro',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
