# Generated by Django 2.1.2 on 2019-01-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_related_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_pro',
        ),
    ]
