# Generated by Django 2.1.2 on 2019-01-01 14:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0016_auto_20190101_2325'),
        ('accounts', '0018_auto_20190101_2325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_remove_product_related_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=200, verbose_name='제목')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='간략설명')),
                ('cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='정가')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='할인가격')),
                ('isSale', models.BooleanField(blank=True, default=False, null=True, verbose_name='판매여부')),
                ('sample', models.URLField(blank=True, null=True, verbose_name='샘플영상')),
                ('isShow', models.BooleanField(blank=True, default=False, null=True, verbose_name='노출여부')),
                ('isDiscount', models.BooleanField(blank=True, default=False, null=True, verbose_name='할인')),
                ('recommend', models.IntegerField(blank=True, choices=[(1, '인기'), (2, '추천')], null=True, verbose_name='추천')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='content_file/%Y/%m/%d', verbose_name='파일')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='파일설명')),
                ('content', models.ManyToManyField(to='products.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='content_image/%Y/%m/%d', verbose_name='샘플이미지')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='사진설명')),
                ('content', models.ManyToManyField(to='products.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=6000)),
                ('register_from', models.DateField(blank=True, null=True)),
                ('register_to', models.DateField(blank=True, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('teacher', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_lec',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(default='', max_length=200, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='no title', max_length=200, verbose_name='제목'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AddField(
            model_name='content',
            name='related_content',
            field=models.ManyToManyField(to='products.Content'),
        ),
    ]
