# Generated by Django 2.1.2 on 2019-01-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190101_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
    ]
