# Generated by Django 2.1.2 on 2019-01-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190102_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replychapter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replychapter',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='ReplyChapter',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
