# Generated by Django 2.1.2 on 2019-01-01 16:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20190102_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=3000, verbose_name='내용'),
        ),
    ]
