# Generated by Django 2.1.2 on 2019-01-01 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20190102_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='products.File'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='products.Image'),
        ),
        migrations.AlterField(
            model_name='content',
            name='related_content',
            field=models.ManyToManyField(blank=True, null=True, to='products.Content'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
