# Generated by Django 2.1.2 on 2019-01-03 05:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20190102_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=8000, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='product',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=8000, verbose_name='내용'),
        ),
    ]
