# Generated by Django 2.1.2 on 2019-01-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20190103_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-category',)},
        ),
    ]
