# Generated by Django 2.1.2 on 2019-01-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20190107_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='확장자'),
        ),
    ]
