# Generated by Django 2.1.2 on 2019-01-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('section',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, default='no title', max_length=200, verbose_name='제목'),
        ),
    ]
