# Generated by Django 2.1.2 on 2019-01-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
