# Generated by Django 2.1.2 on 2019-01-18 06:06

from django.db import migrations, models
from memaker.utils import unique_slug_generator

def update_slug_category(apps, schema_eiditor):
    Category = apps.get_model("products","Category")

    for instance in Category.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.title, instance.slug)
            instance.save()
def update_slug_content(apps, schema_eiditor):
    Content = apps.get_model("products","Content")

    for instance in Content.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.title, instance.slug)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20190118_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.RunPython(update_slug_category, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.RunPython(update_slug_content, reverse_code=migrations.RunPython.noop)
    ]