# Generated by Django 2.1.2 on 2019-01-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20190118_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(db_index=True, default='no title', max_length=200, verbose_name='제목'),
        ),
    ]
