# Generated by Django 2.1.2 on 2019-01-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20190118_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='content',
            index_together={('id', 'slug')},
        ),
    ]
