# Generated by Django 2.1.3 on 2019-01-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20190118_1546'),
        ('products', '0044_auto_20190118_1542'),
    ]

    operations = [
    ]
