# Generated by Django 2.1.2 on 2019-02-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20190221_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='재고'),
        ),
    ]
