# Generated by Django 2.1.2 on 2019-02-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20190221_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='할인가격'),
        ),
    ]
